services:
  postgres-db:
    image: postgres:latest
    container_name: trust-engine-db
    environment:
      POSTGRES_USER: felipe_user
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: trust_engine_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
      image: redis:alpine
      container_name: trustengine-redis
      ports:
        - "6379:6379"
      restart: always
      

  rabbitmq:
    image: rabbitmq:3-management
    container_name: trustengine-rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672" 
    restart: always

volumes:
  postgres_data: