services:
  postgres-db:
    image: postgres:latest
    container_name: trust-engine-db
    environment:
      POSTGRES_USER: felipe_user
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: trust_engine_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: